services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ipedis\Bundle\Rabbit\Service\OrderConnectable:
    abstract: true
    arguments:
      $connectionConfig: "%ipedis_rabbit.connection%"
      $exchangeConfig: "%ipedis_rabbit.order%"

  Ipedis\Bundle\Rabbit\Service\EventConnectable:
    abstract: true
    arguments:
      $connectionConfig: "%ipedis_rabbit.connection%"
      $exchangeConfig: "%ipedis_rabbit.event%"
