services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ipedis\Bundle\Rabbit\Service\Connectable:
    abstract: true
    arguments:
      $host: "%ipedis_rabbit.connection.host%"
      $port: "%ipedis_rabbit.connection.port%"
      $user: "%ipedis_rabbit.connection.user%"
      $password: "%ipedis_rabbit.connection.password%"
      $exchange: "%ipedis_rabbit.order.exchange%"
      $type: "%ipedis_rabbit.order.type%"