pipelines:
  pull-requests:
    '**':
      - step:
          name: "Unit test"
          image: yanisipedis/php7.4-amqp:0.2
          script:
            - sed -i 's/bitbucket:ipedis/git@bitbucket.org:ipedis/g' composer.json
            - sed -i 's/bitbucket:ipedis/git@bitbucket.org:ipedis/g' composer.lock
            - composer install
            - php vendor/bin/pest tests

          caches:
            - composer
