name: Unit Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    container:
      image: yanisipedis/php7.4-amqp:0.2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Run tests
        run: php vendor/bin/pest tests
